<?php


namespace App\V1\Admin\Controllers;

use App\V1\Basis\BaseController;
use Dingo\Api\Http\Request;
use Illuminate\Support\Facades\Cache;

class IndexController extends BaseController
{
    public function index($path = './')
    {
        //你想要哪个文件夹下面的注释生成对应的API文档
        return parent::index(__DIR__); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\OpenApi(
     *     @OA\Server(
     *         url="http://192.168.1.34/api/admin",
     *         description="Localhost Fiction API server"
     *     ),
     *     @OA\Server(
     *         url="http://47.56.151.114:9101/api/admin",
     *         description="Online Fiction API server"
     *     ),
     *     @OA\Info(
     *         version="1.0.0",
     *         title="Fiction Admin",
     *         @OA\Contact(name="Crazypeak")
     *     )
     * )
     * @OA\Schema(
     *     schema="PageModel",
     *     required={"per_page", "last_page", "current_page", "count", "total"},
     *     @OA\Property(
     *         property="data",
     *         description="列表数据",
     *         type="object"
     *     ),
     *     @OA\Property(
     *         property="per_page",
     *         description="每页的数据条数",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="current_page",
     *         description="当前页页码",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="count",
     *         description="当前页数据的数量",
     *         type="integer"
     *     )
     * )
     * @OA\Tag(
     *     name="Default",
     *     description="公用接口(#默认)"
     * )
     * @OA\Tag(
     *     name="Category",
     *     description="书本分类模块"
     * )
     * @OA\Tag(
     *     name="Articles",
     *     description="书本模块"
     * )
     * @OA\Tag(
     *     name="Chapters",
     *     description="书本章节模块"
     * )
     * @OA\Tag(
     *     name="Users",
     *     description="用户模块"
     * )
     * @OA\Tag(
     *     name="Invalid",
     *     description="测试接口，不作项目用"
     * )
     * @OA\SecurityScheme(
     *   securityScheme="Token",
     *   type="apiKey",
     *   in="header",
     *   name="Authorization"
     * )
     */

    /**
     * @OA\Post(
     *     path="/files",
     *     tags={"Default"},
     *     summary="公用上传文件",
     *     security={
     *          {
     *              "Token":{}
     *          }
     *      },
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="multipart/form-data",
     *             @OA\Schema(
     *                 type="object",
     *                 required={"file"},
     *                 @OA\Property(
     *                     property="file",
     *                     description="上传文件对象",
     *                     type="file",
     *                 )
     *             ),
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *              @OA\Property(property="file_path", type="string", description="文件对象路径"),
     *              @OA\Property(property="file_url", type="string", description="文件访问链接")
     *         )
     *        )
     *     )
     * )
     */

    /**
     * @OA\Get(
     *     path="/captcha",
     *     tags={"Default"},
     *     summary="获取验证码",
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *              @OA\Property(property="code", type="integer", description="业务状态码"),
     *              @OA\Property(property="mssgse", type="string", description="描述"),
     *              @OA\Property(property="status_code", type="integer", description="接口状态码"),
     *              @OA\Property(property="version", type="string", description="版本号"),
     *              @OA\Property(property="data",type="object",description="返回数据",
     *                 @OA\Property(property="key",type="string",description="验证码api凭证"),
     *                 @OA\Property(property="img",type="string",description="验证码图片base64")
     *              ),
     *            ),
     *         example={"code": 0,"message": "图形验证码","status_code": 200,"version": "v1","data": {"captcha_url": "http://127.0.0.100/captcha/default?aZduQ0hn"}}
     *        )
     *     )
     * )
     */

    /**
     * @OA\Put(
     *     path="/captcha",
     *     tags={"Invalid"},
     *     summary="测试验证码用(#非正式接口)",
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/x-www-form-urlencoded",
     *             @OA\Schema(
     *                 type="object",
     *                 required={"key","captcha"},
     *                 @OA\Property(
     *                     property="key",
     *                     description="验证码api凭证",
     *                     type="string",
     *                 ),
     *                 @OA\Property(
     *                     property="captcha",
     *                     description="验证码",
     *                     type="string",
     *                 )
     *             ),
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *              @OA\Property(property="code", type="integer", description="业务状态码"),
     *              @OA\Property(property="mssgse", type="string", description="描述"),
     *              @OA\Property(property="status_code", type="integer", description="接口状态码"),
     *              @OA\Property(property="version", type="string", description="版本号"),
     *              @OA\Property(property="data",type="object",description="返回数据"),
     *         )
     *        )
     *     )
     * )
     */

    /**
     * @OA\Get(
     *     path="/config",
     *     tags={"Default"},
     *     summary="获取网站基础设置参数",
     *     security={{"Token":{}}},
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *              @OA\Property(property="web_name", type="integer", description="网站站名#即{web_name}，用于调用"),
     *              @OA\Property(property="web_icon", type="string", description="网站icon"),
     *              @OA\Property(property="web_desc", type="string", description="网站简介"),
     *              @OA\Property(property="file_dir", type="integer", description="默认保存目录"),
     *              @OA\Property(property="views_between", type="string", description="阅读量虚拟#3-10表示随机增加3到10之间的点击数。如需固定请填写如1-1"),
     *              @OA\Property(property="throttle", type="integer", description="搜索时间限制#一分钟只能搜索N次，0则关闭搜索"),
     *              @OA\Property(property="open_ad", type="integer", description="是否开启广告"),
     *              @OA\Property(property="cache_select_time", type="integer", description="列表or搜索缓存时间#单位：秒"),
     *              @OA\Property(property="cache_chapter_time", type="integer", description="章节列表缓存时间#单位：秒")
     *            )
     *        )
     *     )
     * )
     */
    public function getConfig(){
        $config = Cache::get('config',[]);
        if (!$config){
            foreach (\App\Config::all(['key','value']) as $item) $config[$item['key']] = $item['value'];
        }

        return $this->apiReturn('网站基础设置',200,0,$config);
    }

    /**
     * @OA\Put(
     *     path="/config",
     *     tags={"Default"},
     *     summary="修改网站基础设置",
     *     security={{"Token":{}}},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/x-www-form-urlencoded",
     *             @OA\Schema(
     *                 type="object",
     *                 @OA\Property(
     *                     property="web_name",
     *                     description="网站站名#即{web_name}，用于调用",
     *                     default="昊天游小说",
     *                     type="string"
     *                 ),
     *                 @OA\Property(
     *                     property="web_icon",
     *                     description="网站icon",
     *                     default="/storage/default/PxqcYtfQZX52IvfA87dprTnCfwiYEN8jcBJgVvxb.jpeg",
     *                     type="string"
     *                 ),
     *                 @OA\Property(
     *                     property="web_desc",
     *                     description="网站简介",
     *                     default="看小说不用愁",
     *                     type="string"
     *                 ),
     *                 @OA\Property(
     *                     property="file_dir",
     *                     description="默认保存目录",
     *                     default="default",
     *                     type="string"
     *                 ),
     *                 @OA\Property(
     *                     property="views_between",
     *                     description="阅读量虚拟#3-10表示随机增加3到10之间的点击数。如需固定请填写如1-1",
     *                     default="1-1",
     *                     type="string"
     *                 ),
     *                 @OA\Property(
     *                     property="throttle",
     *                     description="搜索时间限制#一分钟只能搜索N次，0则关闭搜索",
     *                     default="10",
     *                     type="integer"
     *                 ),
     *                 @OA\Property(
     *                     property="open_ad",
     *                     description="是否开启广告",
     *                     type="integer",
     *                     default="1",
     *                     enum={"1","0"}
     *                 ),
     *                 @OA\Property(
     *                     property="cache_select_time",
     *                     description="列表or搜索缓存时间#单位：秒",
     *                     default="600",
     *                     type="integer",
     *                 ),
     *                 @OA\Property(
     *                     property="cache_chapter_time",
     *                     description="章节列表缓存时间#单位：秒",
     *                     default="600",
     *                     type="integer",
     *                 )
     *             ),
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功"
     *     )
     * )
     */
    public function putConfig(Request $request)
    {
        $columns = [
            'web_name' => 'string|max:64',
            'web_icon' => 'string|max:64',
            'web_desc' => 'string|max:512',
            'file_dir' => 'string|max:64',
            'views_between' => 'string|max:64',
            'throttle' => 'integer|max:3600',
            'open_ad' => 'integer|max:1',
            'cache_select_time' => 'integer',
            'cache_chapter_time' => 'integer'
        ];

        $request->validate($columns);
        $data = $this->sortRequest($request->input(),$columns);

        foreach ($data as $key => $item){
            \App\Config::updateOrCreate(['key'=>$key],['value'=>$item]);
        }

        $config = [];
        foreach (\App\Config::all(['key','value']) as $item) $config['env.'.$item['key']] = $item['value'];
        Cache::forever('config',$config);

        return $this->apiReturn('操作成功',200,0);
    }

}
