<?php

namespace App\Admin\Controllers;

use Encore\Admin\Grid;
use Encore\Admin\Form;
use Encore\Admin\Layout\Content;
use Illuminate\Support\Facades\Request;
use App\Admin\Models\ArticlesChaptersModel;
use Encore\Admin\Controllers\AdminController;

class ArticlesChaptersController extends AdminController {

    function __construct() {
        define('ARTICLE_ID',Request::route('article_id',0));
    }

    /**
     * {@inheritdoc}
     */
    protected function title()
    {
        return trans('fiction.book').trans('fiction.chapter');
    }

    public function edit($id, Content $content)
    {
        return parent::edit(Request::route('chapter',0), $content); // TODO: Change the autogenerated stub
    }

    public function update($id)
    {
        return parent::update(Request::route('chapter',0));
    }

    public function destroy($id)
    {
        $articlesChaptersModel = new ArticlesChaptersModel();
        try {
            $articlesChaptersModel->destroyArr(Request::route('chapter',0));
            $response = [
                'status'  => true,
                'message' => trans('admin.delete_succeeded'),
            ];
        } catch (\Exception $exception) {
            $response = [
                'status'  => false,
                'message' => $exception->getMessage() ?: trans('admin.delete_failed'),
            ];
        }

        return response()->json($response);
    }

    public function form()
    {
        $form = new Form(new ArticlesChaptersModel());

        $form->display('id', 'ID');
        $form->text('title', trans('admin.title'))->rules('required|max:64');
        $form->text('link', trans('fiction.url'))->rules('max:64')->default('');
        $form->ckeditor('content', trans('fiction.content'))->default('&nbsp;&nbsp;')->rules('max:20480');

        return $form;
    }

    protected function grid()
    {
        $grid = new Grid(new ArticlesChaptersModel());
        $grid->disableFilter();
        $grid->actions(function ($actions) {
            // 去掉查看
            $actions->disableView();
            $actions->disableDelete();
        });

        $grid->id('ID');
        $grid->column('title', trans('admin.title'));
        $grid->column('link', trans('fiction.url'));

        return $grid;
    }
}


