<?php


namespace App\V1\App\Controllers;

use App\V1\Basis\BaseController;

class IndexController extends BaseController
{
    /**
     * @OA\OpenApi(
     *     @OA\Server(
     *         url="http://fiction.crazypeak.im/api/app",
     *         description="Fiction API server"
     *     ),
     *     @OA\Info(
     *         version="1.0.0",
     *         title="Fiction App",
     *         @OA\Contact(name="Crazypeak")
     *     )
     * )
     * @OA\Schema(
     *     schema="TypeModel",
     *     required={"push", "news", "rank","mothor_rank","week_rank"},
     *     @OA\Property(
     *         property="data",
     *         description="排序选择元素",
     *         type="object"
     *     ),
     * )
     * @OA\Schema(
     *     schema="PageModel",
     *     required={"per_page", "last_page", "current_page", "count", "total"},
     *     @OA\Property(
     *         property="data",
     *         description="列表数据",
     *         type="object"
     *     ),
     *     @OA\Property(
     *         property="per_page",
     *         description="每页的数据条数",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="last_page",
     *         description="最后一页的页码",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="current_page",
     *         description="当前页页码",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="count",
     *         description="当前页数据的数量",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="total",
     *         description="数据总数",
     *         type="integer"
     *     )
     * )
     * @OA\Tag(
     *     name="Default",
     *     description="公用接口(#默认)"
     * )
     * @OA\SecurityScheme(
     *   securityScheme="Token",
     *   type="apiKey",
     *   in="header",
     *   name="Authorization"
     * )
     */
    public function index($path = './')
    {
        //你想要哪个文件夹下面的注释生成对应的API文档
        return parent::index(__DIR__); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Post(
     *     path="/files",
     *     tags={"Default"},
     *     summary="公用上传文件",
     *     security={
     *          {
     *              "Token":{}
     *          }
     *      },
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="multipart/form-data",
     *             @OA\Schema(
     *                 type="object",
     *                 required={"file"},
     *                 @OA\Property(
     *                     property="file",
     *                     description="上传文件对象",
     *                     type="file",
     *                 )
     *             ),
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *              @OA\Property(property="file_path", type="string", description="文件对象路径"),
     *              @OA\Property(property="file_url", type="string", description="文件访问链接")
     *         )
     *        )
     *     )
     * )
     */
}
