<?php

namespace App\V1\App\Controllers;

use App\Rules\mobile;
use Dingo\Api\Http\Request;
use App\V1\Basis\BaseController;
use App\V1\Basis\ReptileModel;
use Illuminate\Support\Facades\Cache;

class IndexController extends BaseController
{
    /**
     * @OA\Get(
     *     path="/test",
     *     tags={"Invalid"},
     *     summary="清空redis缓存",
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功"
     *        )
     *     )
     * )
     */
    public function test(){


        $reptile = new ReptileModel();
        return $reptile->getChapter(13,'','https://www.35kushu.com/35zwhtml/96/96500/14383986.html');
        return [date('Y-m-d H:i:s')];

        return config('env');
        return Cache::store('redis')->get('config');
        Cache::flush();
        return $this->apiReturn('成功',200,0);
    }

    public function index($path = './')
    {
        //你想要哪个文件夹下面的注释生成对应的API文档
        return parent::index(__DIR__); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Get(
     *     path="/config",
     *     tags={"Default"},
     *     summary="获取网站基础设置参数",
     *     security={{"Token":{}}},
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *              @OA\Property(property="web_name", type="integer", description="网站站名#即{webname}，用于调用"),
     *              @OA\Property(property="web_icon", type="string", description="网站icon"),
     *              @OA\Property(property="web_desc", type="string", description="网站简介")
     *            )
     *        )
     *     )
     * )
     */
    public function getConfig(){
        $config['web_name'] = config('env.web_name');
        $config['web_icon'] = config('env.web_icon');
        $config['web_desc'] = config('env.web_desc');

        return $this->apiReturn('成功',200,0,$config);
    }

    /**
     * @OA\OpenApi(
     *     @OA\Server(
     *         url="http://192.168.1.34/api/app",
     *         description="Localhost Fiction API server"
     *     ),
     *     @OA\Server(
     *         url="http://47.56.151.114:9101/api/app",
     *         description="Online Fiction API server"
     *     ),
     *     @OA\Info(
     *         version="1.0.0",
     *         title="Fiction App",
     *         @OA\Contact(name="Crazypeak")
     *     )
     * )
     * @OA\Schema(
     *     schema="ResponseModel",
     *     required={"code", "status_code", "message", "version", "data"},
     *     @OA\Property(
     *         property="code",
     *         description="业务代码，一般为0",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="status_code",
     *         description="http状态码",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="message",
     *         description="通知信息",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="version",
     *         description="版本号",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="data",
     *         description="返回数据",
     *         type="object"
     *     )
     * )
     * @OA\Schema(
     *     schema="PageModel",
     *     required={"per_page", "last_page", "current_page", "count", "total"},
     *     @OA\Property(
     *         property="data",
     *         description="列表数据",
     *         type="object"
     *     ),
     *     @OA\Property(
     *         property="per_page",
     *         description="每页的数据条数",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="last_page",
     *         description="最后一页码",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="current_page",
     *         description="当前页页码",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="count",
     *         description="当前页数据的数量",
     *         type="integer"
     *     ),
     *     @OA\Property(
     *         property="total",
     *         description="总数",
     *         type="integer"
     *     )
     * )
     * @OA\Tag(
     *     name="Default",
     *     description="公用接口(#默认)"
     * )
     * @OA\Tag(
     *     name="Articles",
     *     description="文章模块"
     * )
     * @OA\Tag(
     *     name="Users",
     *     description="用户模块"
     * )
     * @OA\Tag(
     *     name="Invalid",
     *     description="测试接口，不作项目用"
     * )
     * @OA\SecurityScheme(
     *   securityScheme="Token",
     *   type="apiKey",
     *   in="header",
     *   name="Authorization"
     * )
     */

    /**
     * @OA\Post(
     *     path="/files",
     *     tags={"Default"},
     *     summary="公用上传文件",
     *     security={
     *          {
     *              "Token":{}
     *          }
     *      },
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="multipart/form-data",
     *             @OA\Schema(
     *                 type="object",
     *                 required={"file"},
     *                 @OA\Property(
     *                     property="file",
     *                     description="上传文件对象",
     *                     type="file",
     *                 )
     *             ),
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *              @OA\Property(property="file_path", type="string", description="文件对象路径"),
     *              @OA\Property(property="file_url", type="string", description="文件访问链接")
     *         )
     *        )
     *     )
     * )
     */

    /**
     * @OA\Get(
     *     path="/captcha",
     *     tags={"Default"},
     *     summary="获取图形验证码",
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *              @OA\Property(property="code", type="integer", description="业务状态码"),
     *              @OA\Property(property="mssgse", type="string", description="描述"),
     *              @OA\Property(property="status_code", type="integer", description="接口状态码"),
     *              @OA\Property(property="version", type="string", description="版本号"),
     *              @OA\Property(property="data",type="object",description="返回数据",
     *                 @OA\Property(property="key",type="string",description="验证码api凭证"),
     *                 @OA\Property(property="img",type="string",description="验证码图片base64")
     *             ),
     *         ),
     *         example={"code": 0,"message": "图形验证码","status_code": 200,"version": "v1","data": {"captcha_url": "http://127.0.0.100/captcha/default?aZduQ0hn"}}
     *        )
     *     )
     * )
     */

    /**
     * @OA\Put(
     *     path="/captcha",
     *     tags={"Invalid"},
     *     summary="测试图形验证码用",
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/x-www-form-urlencoded",
     *             @OA\Schema(
     *                 type="object",
     *                 required={"key","captcha"},
     *                 @OA\Property(
     *                     property="key",
     *                     description="验证码api凭证",
     *                     type="string",
     *                 ),
     *                 @OA\Property(
     *                     property="captcha",
     *                     description="验证码",
     *                     type="string",
     *                 )
     *             ),
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *              @OA\Property(property="code", type="integer", description="业务状态码"),
     *              @OA\Property(property="mssgse", type="string", description="描述"),
     *              @OA\Property(property="status_code", type="integer", description="接口状态码"),
     *              @OA\Property(property="version", type="string", description="版本号"),
     *              @OA\Property(property="data",type="object",description="返回数据"),
     *         )
     *        )
     *     )
     * )
     */

    /**
     * @OA\post(
     *     path="/captcha/sms",
     *     tags={"Default"},
     *     summary="获取短信验证码",
     *     description="开发期间假想验证码：888888",
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/x-www-form-urlencoded",
     *             @OA\Schema(
     *                 type="object",
     *                 required={"mobile"},
     *                 @OA\Property(
     *                     property="mobile",
     *                     description="手机号",
     *                     default="+86",
     *                     type="string",
     *                 ),
     *                 @OA\Property(
     *                     property="key",
     *                     description="验证码api凭证",
     *                     type="string",
     *                 ),
     *                 @OA\Property(
     *                     property="captcha",
     *                     description="验证码",
     *                     type="string",
     *                 )
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功"
     *        )
     *     )
     * )
     */
    public function sendSms(Request $request){

        //验证码验证
        if (!captcha_api_check($request->input('captcha'), $request->input('key'))) return $this->apiReturn('验证码检验不通过', 401, 10);

        $mobile = $request->validate(['mobile'=>['required','string',new mobile()]])['mobile'];
        Cache::put(md5($mobile),888888,600);

        return $this->apiReturn(' 验证码已发送，请关注手机接收', 200, 0);
    }

    /**
     * @OA\put(
     *     path="/captcha/sms",
     *     tags={"Invalid"},
     *     summary="测试短信验证码用",
     *     description="开发期间假想验证码：888888",
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/x-www-form-urlencoded",
     *             @OA\Schema(
     *                 type="object",
     *                 required={"mobile"},
     *                 @OA\Property(
     *                     property="mobile",
     *                     description="手机号,限制中国大陆mobileCode",
     *                     default="",
     *                     type="string",
     *                 ),
     *                 @OA\Property(
     *                     property="sms_code",
     *                     description="短信验证码",
     *                     default="888888",
     *                     type="integer",
     *                 )
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="SUCCESS/成功"
     *        )
     *     )
     * )
     */
    public function validateSms(Request $request){
        $request = $request->validate([
            'mobile'=>'required|mobile',
            'sms_code'=>'required|max:6'
        ]);

        if (Cache::get(md5($request['mobile'])) === $request['sms_code'])
            return $this->apiReturn('短信验证码成功', 200, 0);
        else
            return $this->apiReturn('短信验证码失败',401,10);
    }
}
